name: ai_study_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.2
  flick_video_player: ^0.7.0
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.4
  visibility_detector: ^0.4.0+2
  flutter_screenutil: ^5.9.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.4
  intl: ^0.19.0
  firebase_core: ^2.31.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/jpg/
